apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front 
  template:
    metadata:
      name: nginx
      labels:
        type: front 
        team: ui
    spec:
      containers:
      - image: nginx:1.24
        name: nginx-front-end
   
 
